{% set name = "marray-python" %}
{% set version = "0.0.11" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/marray/marray-{{ version }}.tar.gz
  sha256: 6e5f03f68e1c8abaa73b95c1db12aaac74cd24d437ebc2f057e26d3abf392ecc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - marray
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/mdhaber/marray
  summary: Masked versions of array API compatible arrays
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mdhaber
